### ISSUE TITLE
the baseline performance around 0.20 meter

### ISSUE THREAD

**Issue by yujianyuanhaha** [MaximilianArnold/CTW2019-PositioningCompetition#1]
just double check that [DistError_vsNbAnt.png](https://github.com/MaximilianArnold/CTW2019-PositioningCompetition/blob/master/2_SanityChecks/DistError_vsNbAnt.png) show the baseline __test distance error__ is around 0.20 meter, do I get it right?

**Comment by MaximilianArnold** [comment]
Hello,

I am not sure where are you seeing 0.2? In the Fig it is 0.36 with an update in CFO its 0.29.

BR

Max Arnold
